stages:
  - publish
  - deploy

gitlab-registry:
  stage: publish
  image:
    name: alpine/helm:3.10.2
    entrypoint: [""]
  tags: 
    - dev    
  variables:
    CHART: nginx-charts
  before_script:
    - apk add git
    - helm plugin install --version=v0.10.3 https://github.com/chartmuseum/helm-push.git
    - >
      helm repo add ${CHART}
      --username ${CI_REGISTRY_USER}
      --password ${CI_REGISTRY_PASSWORD}
      ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/stable
  script:
    - helm package ${CHART}
    - helm cm-push ${CHART}*.tgz ${CHART}
  only:
    refs:
      - main
    changes:
      - nginx-charts/**/*

deploy:
  image:
    name: alpine/helm:3.10.2
    entrypoint: ['']
  stage: deploy
  tags:
    - dev
  variables:
    CHART: nginx-charts
  before_script:
    # - curl -LO https://dl.k8s.io/release/v1.26.0/bin/linux/arm64/kubectl
    # - chmod +x kubectl && mv kubectl /usr/bin/kubectl
    # - kubectl version --client
    # - kubectl config get-contexts
    # - kubectl config use-context dakual/gitlab-ci-helm:dev  
    # - chmod 600 $KUBECONFIG
    - helm lnit --kube-context dakual/gitlab-ci-helm:dev
    - chmod 600 $KUBECONFIG
  script:
    - helm dependency update ${CHART}
    - helm upgrade --install myapp ${CHART} --wait
  dependencies:
    - gitlab-registry
  only:
    refs:
      - main
    changes:
      - nginx-charts/**/*


# deploy:
#   stage: deploy
#   image:
#     name: alpine/helm:3.10.2
#     entrypoint: [""]
#   tags: 
#     - dev    
#   variables:
#     CHART: nginx-charts
#     KUBE_URL: https://127.0.0.1:50701
#     KUBE_CA_PEM_FILE: /Users/daghan/.minikube/ca.crt
#     KUBE_TOKEN:
#     KUBE_NAMESPACE:
#   before_script:
#     - mkdir -p /root/.kube
#     - cp -rf ./minikube/config /root/.kube/config
#     - cp -rf ./minikube/client.crt /root/.kube/client.crt
#     - cp -rf ./minikube/client.key /root/.kube/client.key
#     - cp -rf ./minikube/ca.crt /root/.kube/ca.crt
#     # # install AWS CLI
#     # apk add --no-cache python3 py3-pip \
#     #   && pip3 install --upgrade pip \
#     #   && pip3 install awscli \
#     #   && rm -rf /var/cache/apk/*
#     # # add EKS cluster
#     # aws eks --region eu-central-1 update-kubeconfig --name mycluster
#   script: 
#     - helm dependency update ${CHART}
#     - helm upgrade --install myapp ${CHART} --wait