stages:
  - publish

gitlab-registry:
  stage: publish
  image:
    name: alpine/helm:3.10.2
    entrypoint: [""]
  tags: 
    - dev    
  variables:
    CHART: nginx-charts
  before_script:
    - helm registry login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    - >
      helm repo add ${CHART}
      --username ${CI_REGISTRY_USER}
      --password ${CI_REGISTRY_PASSWORD}
      ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/stable
  script:
    - helm package ${CHART}
    - helm push ${CHART}*.tgz oci://${CI_REGISTRY_IMAGE}/${CHART}
  only:
    refs:
      - main
    changes:
      - nginx-charts/**/*
