stages:
  - deploy

variables:
  APP_NAME: demo-nginx
  NAMESPACE: default

deploy:
  stage: deploy
  image: alpine/helm:3.2.1
  script:
    - helm upgrade ${APP_NAME} ./nginx-charts --install --values=./nginx-charts/values.yaml --namespace ${NAMESPACE}
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
      when: always
  tags:
    - dev
