stages:
  - helm-publish
  - deploy

gitlab-registry:
  stage: helm-publish
  image:
    name: alpine/helm:3.10.2
    entrypoint: [""]
  tags: 
    - dev    
  variables:
    CHART: nginx-charts
  before_script:
    - apk add git
    - helm plugin install --version=v0.10.3 https://github.com/chartmuseum/helm-push.git
    - >
      helm repo add ${CHART}
      --username ${CI_REGISTRY_USER}
      --password ${CI_REGISTRY_PASSWORD}
      ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/stable
  script:
    - helm package ${CHART}
    - helm cm-push ${CHART}*.tgz ${CHART}
  only:
    refs:
      - main
    changes:
      - nginx-charts/**/*

deploy:
  stage: deploy
  image:
    name: alpine/helm:3.10.2
    entrypoint: [""]
  tags: 
    - dev    
  variables:
    CHART: nginx-charts
    KUBE_URL: https://127.0.0.1:50701
    KUBE_CA_PEM_FILE: /Users/daghan/.minikube/ca.crt
    KUBE_TOKEN:
    KUBE_NAMESPACE:
  before_script:
    - mkdir -p /root/.kube
    - cp kube_config /root/.kube/config
  script: 
    - helm dependency update ${CHART}
    - helm upgrade --install myapp ${CHART} --wait