variables:
  CHART: nginx-charts
  APP: nginx-demo
  RUNNER: dev
  AGENT: dakual/gitlab-ci-helm:dev 

image:
  name: alpine/helm:3.10.2
  entrypoint: [""]

.helm:
  before_script:
    - chmod 600 $KUBECONFIG
    - apk add git
    - helm plugin install --version=v0.10.3 https://github.com/chartmuseum/helm-push.git
    - >
      helm repo add ${CHART}
      --username ${CI_REGISTRY_USER}
      --password ${CI_REGISTRY_PASSWORD}
      ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/stable
    - curl -LO https://dl.k8s.io/release/v1.26.0/bin/linux/arm64/kubectl
    - chmod +x kubectl && mv kubectl /usr/bin/kubectl
    - kubectl config get-contexts
    - kubectl config use-context ${AGENT}
  only:
    refs:
      - main
    changes:
      - nginx-charts/**/*

stages:
  - validate
  - publish
  - test
  - deploy
  - destroy

helm-template:
  stage: validate
  extends: .helm
  tags: 
    - ${RUNNER}  
  script:
    - helm template ${CHART}

helm-lint:
  stage: validate
  extends: .helm
  tags: 
    - ${RUNNER}
  script:
    - helm lint ${CHART}

push-registry:
  stage: publish
  extends: .helm
  tags: 
    - ${RUNNER}
  script:
    - helm package ${CHART}
    - helm cm-push ${CHART}*.tgz ${CHART}
  artifacts:
    paths:
      - ${CHART}*.tgz

helm-dry-run:
  stage: test
  extends: .helm
  tags: 
    - ${RUNNER}  
  script:
    - helm dependency update ${CHART}
    - helm upgrade --install ${APP} ${CHART} --dry-run --wait
  dependencies:
    - push-registry


helm-install:
  stage: deploy
  extends: .helm
  tags: 
    - ${RUNNER}  
  script:
    - helm dependency update ${CHART}
    - helm upgrade --install ${APP} ${CHART} --wait
  dependencies:
    - push-registry

helm-uninstall:
  stage: destroy
  extends: .helm
  tags:
    - ${RUNNER}
  script:
    - helm uninstall ${APP}
  when: manual