stages:
  - package-publish

helm-package:
  stage: package-publish
  image:
    name: alpine/helm:3.5.3
    entrypoint: [""]
  tags: 
    - dev    
  variables:
    CHART: nginx-charts
  before_script:
    - >
      helm repo add ${CHART}
      --username ${CI_REGISTRY_USER}
      --password ${CI_REGISTRY_PASSWORD}
      ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/stable
  script:
    - helm package ${CHART}
    - helm push ${CHART}*.tgz ${CHART}
  only:
    refs:
      - main
    changes:
      - nginx-charts/**/*