name: nginx-demo
hostName: app.example.com
replicas: 1

image:
  name: nginx
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  name: http

resources:
  requests:
    cpu: 100m
    memory: 100Mi
    